### ISSUE TITLE
problema ao obter variavel do .env que não foi declarada

### ISSUE THREAD

**Issue by flpcoliveira** [motamonteiro/sefaz-portal#1]
Ao tentar obter uma variável do **.env** que não foi declarada, o sistema retorna **null** como padrão. 

Efetuar manutenção para definir um valor padrão diferente de **null** quando a variável de ambiente não for encontrada.

**Comment by motamonteiro** [comment]
Problema resolvido na versao [0.09](https://github.com/motamonteiro/sefaz-portal/commit/601f6736747cd9d7977ec14239047612e86dc366)
